# 工具生成cron表达式: https://cron.qqe2.com/
##############################
###        cron表达式       ###
##############################
#
#    *  *  *  *  *  ?  [非必填]
#    |  |  |  |  |  |  |
#    秒 分  时 日 月 周  年
#
#   参数范围：
#   秒（0 - 59）
#   分（0 - 59）
#   时（0 - 23）
#   日（1 - 31）
#   月（1 - 12 或 JAN-DEC）
#   周（0 - 7 或 SUN-SAT）
#   （可选）年份
#
#   特殊符号：
#    *：任意值
#    ?：不指定值；在 Cron 表达式中，日期和星期两个字段通常是互斥的，你要么指定其中一个，要么指定另一个。
#       当你想在其中一个字段设置具体值而在另一个字段上不设置时，? 会很有用。
#    -：范围，如 1-5
#    ,：枚举，如 1,5,10
#    /：步进，如 */5（表示每5个单位）
#
#   常用示例：
#   0/2 * * * * ?   表示每2秒 执行任务
#   0 0/2 * * * ?    表示每2分钟 执行任务
#   0 0 2 1 * ?   表示在每月的1日的凌晨2点调整任务
#   0 15 10 ? * MON-FRI   表示周一到周五每天上午10:15执行作业
#
##############################
###         注意事项        ###
##############################
# 1.表达式如果设置为相同的时间，将会只执行其中一个

config:
  notice:
    bottom:
      enable: true
      # 消息显示间隔，单位毫秒
      delay-times: 210
      # 消息线程等待超过时长，自动放弃发送消息，单位毫秒
      trylock-times: 60000
      # 消息显示宽度，单位字符
      display-width: 20
    center:
tasks:
  refresh-map:
    enable: true
    name: '定时刷新地图'
    cron: ''
  notice:
    msg1:
      enable: true
      cron: '0/2 * * * * ?'
      start: ''
      end: ''
      position: 'center|bottom'
      message: '&a1-秒一次的消息，钟鼓馔玉不足贵，&b&l但愿长醉不愿醒。陈王昔时宴平乐，&c斗酒十千恣欢谑。'
    msg2:
      enable: true
      cron: '1 57 21 * * ?'
      start: ''
      end: ''
      position: 'center|bottom'
      message: '&a2-关关雎鸠，在河之洲。窈窕淑女，君子好逑。参差荇菜，左右流之。窈窕淑女，寤寐求之。求之不得，寤寐思服。悠哉悠哉，辗转反侧。参差荇菜，左右采之。窈窕淑女，琴瑟友之。参差荇菜，左右芼之。窈窕淑女，钟鼓乐之。。'
    msg3:
      enable: true
      cron: '2 57 21 * * ?'
      start: ''
      end: ''
      position: 'center|bottom'
      message: '&b3-汉皇重色思倾国，御宇多年求不得。'
    msg4:
      enable: true
      cron: '3 57 21 * * ?'
      start: ''
      end: ''
      position: 'center|bottom'
      message: '&e4-回眸一笑百媚生，六宫粉黛无颜色。'
commands:
    cm1:
      command: '/void showxxx'
      cron: '* * 10 * ?'
