# 工具生成cron表达式: https://cron.qqe2.com/
#
# #############################
# ######### cron表达式 #########
# #############################
#    *  *  *  *  *  ?  [非必填]
#    |  |  |  |  |  |  |
#    秒 分  时 日 月 周  年
#
#   参数范围：
#   秒（0 - 59）
#   分（0 - 59）
#   时（0 - 23）
#   日（1 - 31）
#   月（1 - 12 或 JAN-DEC）
#   周（0 - 7 或 SUN-SAT）
#   （可选）年份
#
#   特殊符号：
#    *：任意值
#    ?：不指定值；在 Cron 表达式中，日期和星期两个字段通常是互斥的，你要么指定其中一个，要么指定另一个。
#       当你想在其中一个字段设置具体值而在另一个字段上不设置时，? 会很有用。
#    -：范围，如 1-5
#    ,：枚举，如 1,5,10
#    /：步进，如 */5（表示每5个单位）
#
#   常用示例：
#   0/2 * * * * ?   表示每2秒 执行任务
#   0 0/2 * * * ?    表示每2分钟 执行任务
#   0 0 2 1 * ?   表示在每月的1日的凌晨2点调整任务
#   0 15 10 ? * MON-FRI   表示周一到周五每天上午10:15执行作业
#

# 基础配置
config:
  # 是否开启debug,输出日志
  debug: false
  # 重置世界配置
  regen-world:
    # chunky-check-loading: true # 检查是否有未完成的区块加载任务，继续执行加载
    chunky-loading-notice:
      enable: true # 地图预加载进行中提醒开关
      message: '&e【{world-name}】&c正在进行地图预加载，请勿进入服务器，以免影响加载进度！当前进度&e{per}%，&c剩余时间&e{remain-times}'
      delay: 60 # 消息推送间隔，单位秒，建议不要低于30
  # 消息通知配置
  notice:
    actionbar:
      # 滚动消息全局开关，true开 false关
      enable: true
      # 消息滚动速度间隔，单位毫秒
      delay-times: 260
      # 消息太多导致线程排队等待时，等待超过时长，自动放弃发送消息，单位毫秒
      trylock-times: 60000
      # 消息显示宽度，单位字符
      display-width: 50
    title:
      # 标题消息全局开关，true开 false关
      enable: true
      # 显入时长
      fadein: 20
      # 显示时长
      keep: 80
      # 显出时长
      fadeout: 10
  # 活动配置
  activity:
    # 领取礼物后的声音：ENTITY_FIREWORK_ROCKET_TWINKLE ENTITY_FIREWORK_ROCKET_LAUNCH BLOCK_NOTE_BLOCK_BELL BLOCK_NOTE_BLOCK_CHIME ENTITY_EXPERIENCE_ORB_PICKUP
    claimed-sound: 'ENTITY_FIREWORK_ROCKET_TWINKLE'
    # 记录活动按钮位置，
    # 通过指令 /aep act give获得的按钮，然后放置之后记录的位置
    # 注意：暂时需要手动移除
    handle-block-locations: []
    # 定义圣诞雪球总数量，收集满指定数量，即可领取圣诞礼物
    snowball-count: 5
    # 圣诞雪球按钮位置
    handle-snowball-button-locations: []

#定时任务
tasks:
  # 重置世界定时任务【需要安装多世界插件】
  regen-world:
    # 世界名称，指定具体的世界名称，可添加多个世界配置
    zy:
      enable: false
      cron: '0 0 5 * * ?'
      start: '' #若为空则开始时间为1999年，格式 yyyy-MM-dd HH:mm:ss
      end: '' # 若留空则不限制结束时间，格式 yyyy-MM-dd HH:mm:ss
      new-seed: true # 是否创建新的种子。若为false，将忽略random-seed 和 seed 参数
      random-seed: true # 随机种子，new-seed为true时生效
      seed: '' # 指定种子，random-seed为false时生效
      # 是否保持世界原来的规则，例如死亡不掉落、世界难度、火焰蔓延等配置保持与重置世界前一致
      keep-game-rules: true
      # 世界重置后，是否执行预加载地图，【需要安装Chunk插件】
      loaded-chunky: true
      # 预加载地图半径 半径中心点为（0，0）
      loaded-chunky-radius: 500.0
      # 消息名称key。世界重置后，发送指定消息通知。
      # 被指向的消息，将会由程序自动改变消息的属性：enable、start、end、message
      loaded-notice-key: 'regen-msg'
      # 世界重置后，发送通知内容。
      # 该配置会修改消息任务的message值
      loaded-notice-message: '&a【{world-name}】已重置，快去探索新天地吧~'
      # 世界重置后，在延迟多久后发送通知，单位小时
      # 可能有后续的区块预加载任务，设定一个合适的延后提醒时机，在预加载任务完成后再提醒玩家会比较合理
      # 该配置会修改消息任务的start值
      loaded-notice-delay-hours: 6
      # 世界重置后，发送通知持续时长，单位小时
      # 该配置会修改消息任务的end值
      loaded-notice-keep-hours: 24
      # 世界重置后，执行的控制台指令，从上到下按顺序执行。空数据请填入[]
      loaded-run-commands: []
  # 定时消息任务
  notice:
    # 消息名称，名称可自定义，可添加多个消息配置
    msg0:
      enable: false
      cron: '0 0 0/1 * * ?' # 每隔一小时执行一次
      start: '' #若为空则开始时间为1999年，格式 yyyy-MM-dd HH:mm:ss
      end: '' # 若留空则不限制结束时间，格式 yyyy-MM-dd HH:mm:ss
      position: 'actionbar' # 类型: title 、 actionbar
      message: '&a2-关关雎鸠，在河之洲。窈窕淑女，君子好逑。参差荇菜，左右流之。窈窕淑女，寤寐求之。求之不得，寤寐思服。'
      sub-message: '' #子标题消息，仅在position类型为title时生效
    msg1:
      enable: false
      cron: '0/5 * * * * ?' # 每5秒执行一次
      start: ''
      end: ''
      position: 'title'
      message: '&c警告！当前系统正在维护中。'
      sub-message: '&a子标题我是说似乎'
    regen-msg:
      enable: false
      cron: '0 0 0/1 * * ?' # 每隔一小时执行一次
      start: ''
      end: ''
      position: 'actionbar' # 类型
      message: ''
      sub-message: ''
  # 定时广播
  broadcast:
    tip:
      enable: false
      cron: '0 0/25 * * * ?'
      start: ''
      end: ''
      prefix: "&f[ &a&l✓ 游玩提示&f ] &e>>"
      sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # org.bukkit.Sound
      execute-order: 0 # 0顺序执行 1随机执行
      messages: # 消息内容，请勿使用单引号，必须使用双引号
        - "\n&8- 春江潮水连海平，海上明月共潮生。\n&8- 滟滟随波千万里，何处春江无月明。\n&8- "
  # 执行控制台指令任务
  command:
    cm1:
      enable: false
      cron: '0 0 6 * * ?'
      start: ''
      end: ''
      commands:
        - "clean logs 1w" #清理日志文件 clean logs <1d|1w|1mo>(保留时长)

# 物品绑定事件
item-bind-event:
  commands:
    # 自定义唯一key 。
    # op可以通过命令 /aep itembind give key1获取该物品
    # 特殊key: menu。菜单命令。普通玩家可通过命令获取菜单（ /aep givemenu）
    menu:
      enable: true # 是否启用
      material: 'clock' # 物品材质
      display-name: '&#2796e7&l[系统菜单]'
      lore:
        - ''
        - '&7右键打开系统菜单'
      # 执行命令格式： 前缀+空格+命令
      # 前缀：[player] 、[console]
      # 占位符：{player} 玩家名称
      commands:
        - '[player] cd'
      execute-delay: 0 # 执行延迟（针对所有玩家）TODO 暂时没用
      execute-type: 0 # 交互类型： 0物品 1方块按钮（放置方块后交互）
      locations: [] # 方块位置
