tasks:
    refresh-map:
      enable: true
      name: '定时刷新地图'
      cron: ''
    publish-anno:
      enable: true
      speed: 200
      display-width: 20
      name: '定时公告'
      cron: ''
commands:
    cm1:
      command: '/void showxxx'
      cron: '* * 10 * ?'


